vrpn_client_node:
  ros__parameters:
    server: 192.168.50.88
    port: 3883
    frame_id: "world"
    update_frequency: 10.0 #240.0

    # Use the VRPN server's time, or the client's ROS time.
    use_server_time: False 
    broadcast_tf: True

    # Must either specify refresh frequency > 0.0, or a list of trackers to create
    refresh_tracker_frequency: 1.0 #0.2
    